"use client";

import { useEffect, useState } from "react";
import { approvePurchaseOrder, createSupplier, getMe, getPurchaseOrders, getSuppliers, PurchaseOrderListItem, SupplierListItem } from "@/lib/nexora-api";
import { ApiError } from "@/lib/api";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { MoneyDisplay } from "@/components/ui/MoneyDisplay";
import { SearchInput } from "@/components/ui/SearchInput";
import { Pagination } from "@/components/ui/Pagination";
import { Toast } from "@/components/ui/Toast";
import { FileText, Plus, RefreshCw, Truck, Users } from "lucide-react";

const PAGE_SIZE = 25;
const tones: Record<string, "success" | "warning" | "danger" | "info" | "neutral"> = { PendingApproval: "warning", Approved: "info", PartiallyReceived: "info", Received: "success", Cancelled: "danger" };

export default function PurchasingPage() {
  const [tab, setTab] = useState<"orders" | "suppliers">("orders");
  const [orders, setOrders] = useState<PurchaseOrderListItem[]>([]); const [suppliers, setSuppliers] = useState<SupplierListItem[]>([]);
  const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [canApprove, setCanApprove] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [toast, setToast] = useState<string | null>(null); const [supplierOpen, setSupplierOpen] = useState(false); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); setError(null); try { if (tab === "orders") { const r = await getPurchaseOrders({ page, pageSize: PAGE_SIZE }); setOrders(r.items); setTotal(r.totalCount); } else { const r = await getSuppliers({ search, page, pageSize: PAGE_SIZE }); setSuppliers(r.items); setTotal(r.totalCount); } } catch (e) { setError(e instanceof ApiError ? e.message : "Unable to load purchasing data."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [tab, page, search]);
  useEffect(() => { getMe().then(m => setCanApprove(m.permissions.some(p => p.toLowerCase() === "purchasing.approve"))).catch(() => {}); }, []);
  async function approve(id: string, number: string) { try { await approvePurchaseOrder(id); setToast(`${number} approved`); load(); } catch (e) { setToast(e instanceof ApiError ? e.message : "Unable to approve purchase order."); } }
  async function saveSupplier(form: HTMLFormElement) { const fd = new FormData(form); setSaving(true); try { await createSupplier({ name: String(fd.get("name")), email: String(fd.get("email") || ""), phone: String(fd.get("phone") || ""), address: String(fd.get("address") || ""), defaultPaymentTermDays: Number(fd.get("terms") || 30) }); setSupplierOpen(false); setToast("Supplier created successfully"); setPage(1); load(); } catch (e) { setToast(e instanceof ApiError ? e.message : "Unable to create supplier."); } finally { setSaving(false); } }
  const pending = orders.filter(o => o.status === "PendingApproval").length; const approved = orders.filter(o => o.status === "Approved").length;
  return <div className="flex flex-col gap-5 sm:gap-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-page-title font-semibold tracking-tight text-text-primary">Purchasing</div><div className="mt-1 max-w-2xl text-secondary text-text-muted">Control supplier relationships and the Purchase Order → Goods Receipt → Supplier Invoice workflow.</div></div>{tab === "suppliers" && <Button variant="primary" onClick={() => setSupplierOpen(true)}><Plus className="mr-2 h-4 w-4" />Add supplier</Button>}</header>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><MiniStat icon={FileText} label="Purchase orders" value={tab === "orders" ? total : "—"} /><MiniStat icon={Truck} label="Pending approval" value={tab === "orders" ? pending : "—"} /><MiniStat icon={Users} label="Approved / active" value={tab === "orders" ? approved : total} /></div>
    <div className="flex w-fit gap-1 rounded-control bg-surface-secondary p-1"><button onClick={() => { setTab("orders"); setPage(1); }} className={`rounded-control px-4 py-2 text-secondary font-medium transition ${tab === "orders" ? "bg-white text-primary shadow-card" : "text-text-muted hover:text-text-secondary"}`}>Purchase orders</button><button onClick={() => { setTab("suppliers"); setPage(1); }} className={`rounded-control px-4 py-2 text-secondary font-medium transition ${tab === "suppliers" ? "bg-white text-primary shadow-card" : "text-text-muted hover:text-text-secondary"}`}>Suppliers</button></div>
    {toast && <Toast message={toast} onDismiss={() => setToast(null)} />}{tab === "suppliers" && <div className="max-w-xl"><SearchInput placeholder="Search suppliers..." onSearch={v => { setSearch(v); setPage(1); }} /></div>}
    <Card className="overflow-hidden">{loading ? <TableSkeleton /> : error ? <div className="p-10 text-center"><div className="font-medium text-text-primary">Unable to load purchasing data.</div><div className="mt-1 text-secondary text-text-muted">{error}</div><button onClick={load} className="mt-4 inline-flex items-center gap-2 font-medium text-primary"><RefreshCw className="h-4 w-4" />Retry</button></div> : tab === "orders" ? <OrderTable orders={orders} canApprove={canApprove} onApprove={approve} /> : <SupplierTable suppliers={suppliers} />}{!loading && !error && <Pagination page={page} pageSize={PAGE_SIZE} totalCount={total} onPageChange={setPage} />}</Card>
    {supplierOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><form onSubmit={e => { e.preventDefault(); saveSupplier(e.currentTarget); }} className="w-full max-w-lg rounded-dialog bg-white p-6 shadow-dialog"><div className="text-lg font-semibold text-text-primary">Add supplier</div><div className="mt-1 text-secondary text-text-muted">Create a supplier record for purchasing workflows.</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["name","Name","text"],["email","Email","email"],["phone","Phone","text"],["address","Address","text"],["terms","Payment terms (days)","number"]].map(([name,label,type]) => <label key={name} className="text-secondary font-medium text-text-secondary"><span className="mb-1.5 block text-dense">{label}</span><input required={name === "name"} name={name} type={type} defaultValue={name === "terms" ? "30" : ""} className="w-full rounded-input border border-border bg-white px-3 py-2.5 text-body outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" /></label>)}</div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" type="button" onClick={() => setSupplierOpen(false)}>Cancel</Button><Button variant="primary" type="submit" disabled={saving}>{saving ? "Saving..." : "Create supplier"}</Button></div></form></div>}
  </div>;
}
function MiniStat({ icon: Icon, label, value }: { icon: typeof FileText; label: string; value: string | number }) { return <Card className="flex items-center gap-3 p-4"><div className="flex h-10 w-10 items-center justify-center rounded-control bg-primary-soft text-primary"><Icon className="h-5 w-5" /></div><div><div className="text-dense text-text-muted">{label}</div><div className="mt-0.5 text-lg font-semibold tabular-nums text-text-primary">{value}</div></div></Card>; }
function OrderTable({ orders, canApprove, onApprove }: { orders: PurchaseOrderListItem[]; canApprove: boolean; onApprove: (id: string, number: string) => void }) { if (!orders.length) return <div className="p-10 text-center"><div className="font-medium text-text-primary">No purchase orders yet.</div><div className="mt-1 text-secondary text-text-muted">Purchase orders will appear here as they are created.</div></div>; return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-body"><thead><tr className="border-b border-border bg-surface-secondary/60 text-dense text-text-muted"><th className="px-5 py-3 text-left font-medium">Order</th><th className="px-5 py-3 text-left font-medium">Supplier</th><th className="px-5 py-3 text-left font-medium">Date</th><th className="px-5 py-3 text-left font-medium">Status</th><th className="px-5 py-3 text-right font-medium">Total</th><th className="px-5 py-3 text-right font-medium">Action</th></tr></thead><tbody>{orders.map(o => <tr key={o.id} className="border-b border-border last:border-0 hover:bg-surface-secondary/70"><td className="px-5 py-3.5 font-semibold text-text-primary">{o.number}</td><td className="px-5 py-3.5 text-text-secondary">{o.supplierName}</td><td className="px-5 py-3.5 text-text-muted">{o.orderDate}</td><td className="px-5 py-3.5"><StatusBadge label={o.status} tone={tones[o.status] ?? "neutral"} /></td><td className="px-5 py-3.5 text-right font-semibold tabular-nums"><MoneyDisplay amount={o.total} /></td><td className="px-5 py-3.5 text-right">{canApprove && o.status === "PendingApproval" && <Button variant="secondary" onClick={() => onApprove(o.id, o.number)}>Approve</Button>}</td></tr>)}</tbody></table></div>; }
function SupplierTable({ suppliers }: { suppliers: SupplierListItem[] }) { if (!suppliers.length) return <div className="p-10 text-center text-secondary text-text-muted">No suppliers found.</div>; return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-body"><thead><tr className="border-b border-border bg-surface-secondary/60 text-dense text-text-muted"><th className="px-5 py-3 text-left font-medium">Supplier</th><th className="px-5 py-3 text-left font-medium">Email</th><th className="px-5 py-3 text-left font-medium">Phone</th><th className="px-5 py-3 text-left font-medium">Status</th></tr></thead><tbody>{suppliers.map(s => <tr key={s.id} className="border-b border-border last:border-0 hover:bg-surface-secondary/70"><td className="px-5 py-3.5 font-semibold text-text-primary">{s.name}</td><td className="px-5 py-3.5 text-text-secondary">{s.email ?? "—"}</td><td className="px-5 py-3.5 text-text-secondary">{s.phone ?? "—"}</td><td className="px-5 py-3.5"><StatusBadge label={s.isActive ? "Active" : "Inactive"} tone={s.isActive ? "success" : "neutral"} /></td></tr>)}</tbody></table></div>; }
function TableSkeleton() { return <div className="flex flex-col gap-2 p-4">{[0,1,2,3,4].map(i => <div key={i} className="h-12 animate-pulse rounded-control bg-surface-secondary" />)}</div>; }
